### PR TITLE
Fix immediate eviction for default `maxLifeTime`

### LINKED ISSUE #129: Default maxLifeTime value result in immediate eviction of all connections
## Bug Report

The default for maxLifeTime is [defined](https://github.com/r2dbc/r2dbc-pool/blob/main/src/main/java/io/r2dbc/pool/ConnectionPoolConfiguration.java#L47) as `NO_TIMEOUT = Duration.ofNanos(-1)`, which is supposed to mean "No timeout". However, the [current implementation of actual evectionPredicate](https://github.com/r2dbc/r2dbc-pool/blob/main/src/main/java/io/r2dbc/pool/ConnectionPool.java#L191-L196), attempts to do `toMillis` conversion, which results in `0`, thus resulting in the `if (maxIdleTimeMills == 0 || maxLifeTimeMillis == 0)` always returning `true`.

#### Possible Solution

Replace `maxLifeTimeMillis == 0` with `maxLifeTime.isZero()`.

### PR DESCRIPTION
**Pull request by patriknw**
Fixes #129

### CODE REVIEW

File: src/main/java/io/r2dbc/pool/ConnectionPoolConfiguration.java [hunk 1]
```diff
@@ -47,7 +47,7 @@
     /**
      * Constant indicating that timeout should not apply.
      */
-    public static final Duration NO_TIMEOUT = Duration.ofNanos(-1);
+    public static final Duration NO_TIMEOUT = Duration.ofMillis(-1);
```
Comment (patriknw) [inline src/main/java/io/r2dbc/pool/ConnectionPoolConfiguration.java:50]: this change isn't strictly needed, but seems like a safer choice to avoid future similar mistakes

**Comment by patriknw** [comment]
@mp911de friendly ping, if you have a moment to review this fix

**Comment by GabrielCalin** [comment]
@patriknw just a small suggestion, as I've stumbled upon this bug myself, I think it's easier to just replace` if (maxIdleTimeMills == 0 || maxLifeTimeMillis == 0)` with `if (maxIdleTime.isZero() || maxLifeTime.isZero())` in the `evictionPredicate`, this way it's just one line of code changed, the code is easier to read and all tests will pass.

File: src/main/java/io/r2dbc/pool/ConnectionPool.java [hunk 2]
```diff
@@ -209,15 +209,13 @@ private InstrumentedPool<Connection> createConnectionPool(ConnectionPoolConfigur
         // current implementation. (https://github.com/reactor/reactor-pool/issues/33)
         // To workaround the issue, here defines an evictionPredicate that performs both maxIdleTime and maxLifeTime check.
         BiPredicate<Connection, PooledRefMetadata> evictionPredicate = (connection, metadata) -> {
-            long maxIdleTimeMills = maxIdleTime.toMillis();
-            long maxLifeTimeMillis = maxLifeTime.toMillis();
-
-            if (maxIdleTimeMills == 0 || maxLifeTimeMillis == 0) {
+            if (maxIdleTime.isZero() || maxLifeTime.isZero()) {
+                // evict immediately
```
Comment (patriknw) [inline src/main/java/io/r2dbc/pool/ConnectionPool.java:213]: > just a small suggestion, as I've stumbled upon this bug myself, I think it's easier to just replace if (maxIdleTimeMills == 0 || maxLifeTimeMillis == 0) with if (maxIdleTime.isZero() || maxLifeTime.isZero()) in the evictionPredicate, this way it's just one line of code changed, the code is easier to read and all tests will pas

@GabrielCalin isn't that exactly what I changed here?

Comment (GabrielCalin) [reply src/main/java/io/r2dbc/pool/ConnectionPool.java:213]: You're right, I'm not sure why I didn't see it. Hopefully someone will merge it soon. I had to add a very big maximum lifetime at the moment as a workaround.

Comment (patriknw) [reply src/main/java/io/r2dbc/pool/ConnectionPool.java:213]: yes, I'm using that workaround as well. Also note that you have to set a `backgroundEvictionInterval`, otherwise there will be no eviction at all

Comment (GabrielCalin) [reply src/main/java/io/r2dbc/pool/ConnectionPool.java:213]: Oh, thanks, so `maxIdleTime` & 'maxLifeTime' even if explicitly set are not working for background eviction with the default `backgroundEvictionInterval`? (I assume because of the same issue)

**Review by GabrielCalin — APPROVED** [review]

**Comment by cemo** [comment]
@mp911de can you please merge this? This is a serious issue and affect performance badly.

**Review by linghengqian — APPROVED** [review]

File: src/main/java/io/r2dbc/pool/ConnectionPool.java (hunk 2 above)
Comment (Inego) [reply src/main/java/io/r2dbc/pool/ConnectionPool.java:213]: > You're right, I'm not sure why I didn't see it. Hopefully someone will merge it soon. I had to add a very big maximum lifetime at the moment as a workaround.

Isn't `-1` the maximum lifetime value now?

Comment (GabrielCalin) [reply src/main/java/io/r2dbc/pool/ConnectionPool.java:213]: > > ... I had to add a very big maximum lifetime at the moment as a workaround.
> 
> Isn't `-1` the maximum lifetime value now?

Because of the bug, `-1 `gets assimilated to `0`, which means immediate eviction. It's actually why the default value of `-1` doesn't work as expected and instead causes connections to be dropped before each query. The workaround is to set it to a big value, in practice meaning the same as `-1` is supposed to mean, that connections are not expired.

Comment (Inego) [reply src/main/java/io/r2dbc/pool/ConnectionPool.java:213]: Hmm, setting maxLifeTime to -1 actually helped us. With the default maxLifeTime, all connections were instantly expiring, while with -1 they stay forever.

**Comment by mp911de** [comment]
Thank you for your contribution. That's merged and backported now.
